# Shell variables
# Generated by 'wal'
wallpaper='/home/zlin/.config/wpg/wallpapers/key.png'

# Special
background='#0D0D12'
foreground='#9a9abb'
cursor='#9a9abb'

# Colors
color0='#0D0D12'
color1='#443C62'
color2='#58535F'
color3='#534A70'
color4='#D12F32'
color5='#FF3636'
color6='#C35039'
color7='#9a9abb'
color8='#6b6b82'
color9='#443C62'
color10='#58535F'
color11='#534A70'
color12='#D12F32'
color13='#FF3636'
color14='#C35039'
color15='#9a9abb'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
