#!/bin/bash

## Open folders in pcmanfm
FILE="$HOME/.cache/eww_launch.dashboard"
CFG="$HOME/.config/eww/dashboard"
EWW=`which eww`

close_dash() {
	${EWW} --config "$CFG" close \
					background profile system clock uptime music github \
					reddit twitter youtube weather apps mail logout sleep reboot poweroff folders
	rm -rf "$FILE"
}

if [[ "$1" == "--dl" ]]; then
	close_dash && pcmanfm ~/Downloads &

elif [[ "$1" == "--docs" ]]; then
	close_dash && pcmanfm ~/Documents &

elif [[ "$1" == "--music" ]]; then
	close_dash && pcmanfm ~/Music &

elif [[ "$1" == "--pics" ]]; then
	close_dash && pcmanfm ~/Pictures &

elif [[ "$1" == "--cfg" ]]; then
	close_dash && pcmanfm ~/.config &

elif [[ "$1" == "--local" ]]; then
	close_dash && pcmanfm ~/.local/share &

fi
