# Shell variables
# Generated by 'wal'
wallpaper="/home/zlin/Pictures/Wallpapers/wallhaven-g7pw73.jpg"

# Special
background='#161d24'
foreground='#c4c6c8'
cursor='#c4c6c8'

# Colors
color0='#161d24'
color1='#3571C9'
color2='#6D8FA5'
color3='#509FCE'
color4='#A0A6AC'
color5='#E2C1A4'
color6='#9DB7C9'
color7='#93999e'
color8='#606c76'
color9='#7797c5'
color10='#82aec9'
color11='#88b3cc'
color12='#a0bed6'
color13='#e3d0bf'
color14='#aecadc'
color15='#c4c6c8'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
