# Shell variables
# Generated by 'wal'
wallpaper="/home/zlin/Pictures/Wallpapers/wallhaven-g7pw73.jpg"

# Special
background='#161d24'
foreground='#c4c6c8'
cursor='#c4c6c8'

# Colors
color0='#161d24'
color1='#3571C9'
color2='#6D8FA5'
color3='#509FCE'
color4='#A0A6AC'
color5='#E2C1A4'
color6='#9DB7C9'
color7='#93999e'
color8='#606c76'
color9='#7797c5'
color10='#82aec9'
color11='#88b3cc'
color12='#a0bed6'
color13='#e3d0bf'
color14='#aecadc'
color15='#c4c6c8'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
# Colors
accent=$color12
light_value='0.05'
dark_value='0.30'

# Wallpaper
#wdir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
#wallpaper="$wdir/wallpaper"

# Polybar
#~ polybar_font='Iosevka Nerd Font:size=10;3'

# Rofi
rofi_font='Noto Sans 10'
rofi_icon='Gruvbox-Light'

# Terminal
terminal_font_name='NotoSansM Nerd Font Mono'
terminal_font_size='7'

# Geany
geany_colors='wal.conf'
geany_font='NotoSansM Nerd Font Mono 10'

# base16 colors for neovim, qtile, qutebrowser
# set to 'pywal' to use pywal colors
base16_colors='pywal'

# Appearance
gtk_font='Noto Sans 9'
gtk_theme='adw-gtk3-dark'
qt_font='Noto Sans,12'
qt_theme='kvantum'
icon_theme='Papirus-Dark'
cursor_theme=''

# Dunst
dunst_width='300'
dunst_height='80'
dunst_offset='10x42'
dunst_origin='top-right'
dunst_font='Iosevka Custom 9'
dunst_border='1'
dunst_separator='1'

# Picom
picom_backend='glx'
picom_corner='0'
picom_shadow_r='14'
picom_shadow_o='0.30'
picom_shadow_x='-12'
picom_shadow_y='-12'
picom_blur_method='none'
picom_blur_strength='0'

# Qtile
bspwm_fbc="$accent"
bspwm_nbc="$background"
bspwm_abc="$color5"
bspwm_pfc="$color2"
bspwm_border='1'
bspwm_gap='10'
bspwm_sratio='0.50'

# Don't Delete This File
