# Shell variables
# Generated by 'wal'
wallpaper="/home/zlin/Pictures/Wallpapers/g5uf41pcz1h81.png"

# Special
background='#0D0D0E'
foreground='#c2c2c2'
cursor='#c2c2c2'

# Colors
color0='#0D0D0E'
color1='#384848'
color2='#4A504C'
color3='#616A62'
color4='#6D9A6B'
color5='#B68954'
color6='#96A795'
color7='#978c8c'
color8='#57576b'
color9='#429b9b'
color10='#48a960'
color11='#5db96a'
color12='#7ec67c'
color13='#c7a57e'
color14='#9cd398'
color15='#c2c2c2'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
