## Colors configuration
## Default colors
[colors.primary]
background = '#0D0D0E'
foreground = '#c2c2c2'

[colors.normal]
black =   '#0D0D0E'
red =     '#384848'
green =   '#4A504C'
yellow =  '#616A62'
blue =    '#6D9A6B'
magenta = '#B68954'
cyan =    '#96A795'
white =   '#978c8c'

[colors.bright]
black =   '#57576b'
red =     '#429b9b'
green =   '#48a960'
yellow =  '#5db96a'
blue =    '#7ec67c'
magenta = '#c7a57e'
cyan =    '#9cd398'
white =   '#c2c2c2'
