# Shell variables
# Generated by 'wal'
wallpaper="/home/zlin/Pictures/Wallpapers/car.png"

# Special
background='#020914'
foreground='#bfc1c4'
cursor='#bfc1c4'

# Colors
color0='#020914'
color1='#8C6F7E'
color2='#152C96'
color3='#055A97'
color4='#5336C6'
color5='#CA2BCD'
color6='#FB61F8'
color7='#8b8f96'
color8='#565e69'
color9='#c4769f'
color10='#4c5eb2'
color11='#4981aa'
color12='#8777c4'
color13='#c275c3'
color14='#daa9d9'
color15='#bfc1c4'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
# Colors
accent=$color12
light_value='0.05'
dark_value='0.30'

# Wallpaper
#wdir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
#wallpaper="$wdir/wallpaper"

# Polybar
#~ polybar_font='Iosevka Nerd Font:size=10;3'

# Rofi
rofi_font='Noto Sans 10'
rofi_icon='Gruvbox-Light'

# Terminal
terminal_font_name='NotoSansM Nerd Font Mono'
terminal_font_size='7'

# Geany
geany_colors='wal.conf'
geany_font='NotoSansM Nerd Font Mono 10'

# base16 colors for neovim, qtile, qutebrowser
# set to 'pywal' to use pywal colors
base16_colors='pywal'

# Appearance
gtk_font='Noto Sans 9'
gtk_theme='adw-gtk3-dark'
qt_font='Noto Sans,12'
qt_theme='kvantum'
icon_theme='Papirus-Dark'
cursor_theme=''

# Dunst
dunst_width='300'
dunst_height='80'
dunst_offset='10x42'
dunst_origin='top-right'
dunst_font='Iosevka Custom 9'
dunst_border='1'
dunst_separator='1'

# Picom
picom_backend='glx'
picom_corner='0'
picom_shadow_r='14'
picom_shadow_o='0.30'
picom_shadow_x='-12'
picom_shadow_y='-12'
picom_blur_method='none'
picom_blur_strength='0'

# Qtile
bspwm_fbc="$accent"
bspwm_nbc="$background"
bspwm_abc="$color5"
bspwm_pfc="$color2"
bspwm_border='1'
bspwm_gap='10'
bspwm_sratio='0.50'

# Don't Delete This File
