# Shell variables
# Generated by 'wal'
wallpaper="/home/zlin/Pictures/Wallpapers/00279.jpg"

# Special
background='#0c0b0a'
foreground='#c2c2c1'
cursor='#c2c2c1'

# Colors
color0='#0c0b0a'
color1='#504E4B'
color2='#6B625B'
color3='#935938'
color4='#90725C'
color5='#AC926D'
color6='#759095'
color7='#96968a'
color8='#696056'
color9='#aa8948'
color10='#b8825b'
color11='#b97e5d'
color12='#c0926e'
color13='#cbaf85'
color14='#7ebbc7'
color15='#c2c2c1'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
# Colors
accent=$color12
light_value='0.05'
dark_value='0.30'

# Wallpaper
#wdir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
#wallpaper="$wdir/wallpaper"

# Polybar
#~ polybar_font='Iosevka Nerd Font:size=10;3'

# Rofi
rofi_font='Noto Sans 10'
rofi_icon='Gruvbox-Light'

# Terminal
terminal_font_name='NotoSansM Nerd Font Mono'
terminal_font_size='7'

# Geany
geany_colors='wal.conf'
geany_font='NotoSansM Nerd Font Mono 10'

# base16 colors for neovim, qtile, qutebrowser
# set to 'pywal' to use pywal colors
base16_colors='pywal'

# Appearance
gtk_font='Noto Sans 9'
gtk_theme='adw-gtk3-dark'
icon_theme='Gruvbox-Light'
cursor_theme=''

# Dunst
dunst_width='300'
dunst_height='80'
dunst_offset='10x42'
dunst_origin='top-right'
dunst_font='Iosevka Custom 9'
dunst_border='1'
dunst_separator='1'

# Picom
picom_backend='glx'
picom_corner='0'
picom_shadow_r='14'
picom_shadow_o='0.30'
picom_shadow_x='-12'
picom_shadow_y='-12'
picom_blur_method='none'
picom_blur_strength='0'

# Qtile
bspwm_fbc="$accent"
bspwm_nbc="$background"
bspwm_abc="$color5"
bspwm_pfc="$color2"
bspwm_border='1'
bspwm_gap='10'
bspwm_sratio='0.50'

# Don't Delete This File
