--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/zlin/.config/wpg/wallpapers/undefined - Imgur(8).jpg"

-- Special
background="#0F171A"
foreground="#eac5be"
cursor="#eac5be"

-- Colors
color0="#0F171A"
color1="#5F515F"
color2="#A3665B"
color3="#F19D74"
color4="#D2A26C"
color5="#817C87"
color6="#BFA7A8"
color7="#eac5be"
color8="#a38985"
color9="#5F515F"
color10="#A3665B"
color11="#F19D74"
color12="#D2A26C"
color13="#817C87"
color14="#BFA7A8"
color15="#eac5be"
