# Shell variables
# Generated by 'wal'
wallpaper='/home/zlin/.config/wpg/wallpapers/undefined - Imgur(8).jpg'

# Special
background='#0F171A'
foreground='#eac5be'
cursor='#eac5be'

# Colors
color0='#0F171A'
color1='#5F515F'
color2='#A3665B'
color3='#F19D74'
color4='#D2A26C'
color5='#817C87'
color6='#BFA7A8'
color7='#eac5be'
color8='#a38985'
color9='#5F515F'
color10='#A3665B'
color11='#F19D74'
color12='#D2A26C'
color13='#817C87'
color14='#BFA7A8'
color15='#eac5be'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
