# Shell variables
# Generated by 'wal'
wallpaper='/home/zlin/Pictures/city.png'

# Special
background='#05060a'
foreground='#d2d9d8'
cursor='#d2d9d8'

# Colors
color0='#05060a'
color1='#555A5C'
color2='#94876F'
color3='#3D5D81'
color4='#57708C'
color5='#75899C'
color6='#92A1AC'
color7='#d2d9d8'
color8='#939797'
color9='#555A5C'
color10='#94876F'
color11='#3D5D81'
color12='#57708C'
color13='#75899C'
color14='#92A1AC'
color15='#d2d9d8'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
